<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>aissemble-parent</artifactId>
        <version>6</version>
        <relativePath />
    </parent>

    <artifactId>aissemble-universal-config</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <name>aiSSEMBLE::Universal Config</name>
    <description>aiSSEMBLE universal configuration</description>
    <packaging>pom</packaging>

    <distributionManagement>
        <snapshotRepository>
            <id>ghcr.io</id>
            <url>https://maven.pkg.github.com/boozallen/aissemble-universal-config</url>
        </snapshotRepository>
    </distributionManagement>

    <modules>
        <module>aissemble-universal-config-loader</module>
    </modules>

    <properties>
        <version.habushu.plugin>3.1.1</version.habushu.plugin>
        <version.python>3.11.4</version.python>
        <version.maven.release.plugin>3.1.1</version.maven.release.plugin>
    </properties>

    <scm>
        <connection>scm:git:ssh://git@github.com/boozallen/aissemble-universal-config.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/boozallen/aissemble-universal-config.git
        </developerConnection>
        <url>https://github.com/boozallen/aissemble-universal-config/</url>
        <tag>aissemble-universal-config-0.1.0</tag>
    </scm>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.technologybrewery.habushu</groupId>
                    <artifactId>habushu-maven-plugin</artifactId>
                    <version>${version.habushu.plugin}</version>
                    <extensions>true</extensions>
                    <configuration>
                        <pythonVersion>${version.python}</pythonVersion>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>${version.maven.release.plugin}</version>
                    <configuration>
                        <releaseProfiles>central-release</releaseProfiles>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>0.7.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <publishingServerId>central</publishingServerId>
                        <autoPublish>true</autoPublish>
                        <waitUntil>uploaded</waitUntil>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <!-- Apply licenses automatically -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <!-- During release preparation, Habushu will automatically update the versions of Habushu modules
                        within their pyproject.toml configurations, however the maven-release-plugin will only commit
                        updates to pom.xml files.  In order to version control both pom.xml and pyproject.toml files
                        that are updated during release preparation, customize the preparation and completion goals
                        to additionally execute the scm:checkin goals -->
                    <preparationGoals>clean verify scm:checkin -Dmessage="[maven-release-plugin] prepare release"
                    </preparationGoals>
                    <completionGoals>clean verify scm:checkin -Dmessage="[maven-release-plugin] prepare for next
                        development iteration"
                    </completionGoals>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>ci</id>
            <properties>
                <maven.build.cache.enabled>false</maven.build.cache.enabled>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.technologybrewery.habushu</groupId>
                            <artifactId>habushu-maven-plugin</artifactId>
                            <version>${version.habushu.plugin}</version>
                            <configuration>
                                <usePyenv>false</usePyenv>
                                <deleteVirtualEnv>true</deleteVirtualEnv>
                                <forceSync>true</forceSync>
                                <decryptPassword>false</decryptPassword>
                                <rewriteLocalPathDepsInArchives>true</rewriteLocalPathDepsInArchives>
                                <addPypiRepoAsPackageSources>false</addPypiRepoAsPackageSources>
                                <useDevRepository>true</useDevRepository>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>central-release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
